spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: wwhite@saymyname.com
    password: heisenberg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true